#!/bin/mksh

\\builtin set -e

conf=$HOME/etc/wallpaper
dest=$HOME/Pictures/Wallpapers/digitalblasphemy
dist=$HOME/Downloads
temp=$HOME/tmp/wallpaper

\\builtin cat $conf/res.list |&

while \\builtin read -pr res suf
do
	zip=$dist/$res.zip
	[[ -e $zip ]] || \\builtin continue
	dir=$dest/$res
	\mkdir -pv $dir
	\find $dir -type f -print0 | \xargs -0r chmod 755
	\rm -fr $temp
	\mkdir -p $temp
	{
		\\builtin cd $temp
		\7z x $zip
		\find . -type f -print0 | \xargs -0r chmod 644
		\sed "s/\$/$suf.jpg/" <$conf/black.list | \xargs -r rm -f 2>/dev/null || \\builtin :
		\sed "s/\$/$suf.jpg/" <$conf/white.list | \xargs -r mv -f -t $dir 2>/dev/null || \\builtin :
		for file in *$suf.jpg
		do
			[[ -e $file ]] || \\builtin continue
			name=${file%$suf.jpg}
			pid=
			if [[ -n $DISPLAY ]]
			then
				\feh -. $file &
				pid=$!
			fi
			while \\builtin :
			do
				\\builtin print -nr "Keep '$name'? (y/n): " >&2
				\\builtin read -r keep
				case $keep in
				([Yy]*)
					\mv -fv -t $dir $file
					\\builtin print -r -- $name >>$conf/white.list{tmp}
					\\builtin break
					;;
				([Nn]*)
					\rm -fv $file
					\\builtin print -r -- $name >>$conf/black.list{tmp}
					\\builtin break
					;;
				esac
			done
			[[ -n $pid ]] && \\builtin kill $pid || \\builtin :
		done
	}
	\rm -fr $temp
	\find $dir -type f -perm 755 -print0 | \xargs -0r rm -fv
	for i in black white
	do
		list=$conf/$i.list
		if [[ -e $list{tmp} ]]
		then
			\\builtin cat $list $list{tmp} | \sort -u >$list{new}
			\rm -f $list{tmp}
			\diff -u $list $list{new} | \cdiff
			\mv -fv $list{new} $list
		fi
	done
done
