#!/bin/sh

set -e

echo() {
  print -R "$@"
}
warn() {
  echo "$@" 1>&2
}
die() {
  e="$1"
  shift
  warn "$@"
  exit "$e"
}

home="$( cd "$( dirname "$0" )" && env - "PATH=$PATH" pwd )"
wine="$( cd "$home/../.wine" && env - "PATH=$PATH" pwd )"

name="$1"

[[ -d "$home/base/$name" && -d "$home/live/$name" ]] || die 1 "$0: Could not find images for '$name'"

mount -o "ro,noatime,sync,lowerdir=$home/base/system,upperdir=$home/base/$name,workdir=$home/work" -t overlay overlay "$home/base/current"
mount -o "rw,noatime,sync,lowerdir=$home/base/current,upperdir=$home/live/$name,workdir=$home/work" -t overlay overlay "$wine"
