#!/bin/sh

set -e

home="$( cd "$( dirname "$0" )" && env - "PATH=$PATH" pwd )"
wine="$( cd "$home/../.wine" && env - "PATH=$PATH" pwd )"

for dir in "$wine" "$home/base/current"
do
  while ! umount "$dir" 2> /dev/null
  do
    sleep 1
  done
done
