#!/bin/sh

set -e

home="$( cd "$( dirname "$0" )" && env - "PATH=$PATH" pwd )"
wine="$( cd "$home/../.wine" && env - "PATH=$PATH" pwd )"

while ! doas umount "$wine" 2> /dev/null
do
  sleep 1
done

while ! doas umount "$home/base/current" 2> /dev/null
do
  sleep 1
done
