#!/bin/sh

## System
echo '>> Synchronising repository indices'
doas xbps-install -S

echo '>> Updating XBPS'
doas xbps-install -u xbps

echo '>> Updating packages'
doas xbps-install -u

echo '>> Removing orphaned packages'
doas xbps-remove -o

echo '>> Pruning package cache'
doas xbps-remove -O

echo '>> Purging old kernels'
list=$(vkpurge list | sed '$d')
[ -n "$list" ] && doas vkpurge rm $list

echo '>> Updating package list'
list=~/etc/packages.list
xbps-query -m | xargs -n 1 xbps-uhelper getpkgname > $list{new}
cmp -s $list{new} $list || mv -f $list{new} $list
rm -f $list{new}

## Rust
if which rustup > /dev/null 2>&1
then
	echo '>> Updating rust'
	rustup update
fi

## Python
python=$(which python python3 python2 2> /dev/null | head -1)
if [ -n "$python" ]
then
	if ! $python -m pip --version > /dev/null 2>&1
	then
		echo '>> Installing pip'
		$python -m ensurepip --user --default-pip
	fi

	echo '>> Updating pip'
	$python -m pip install --user --upgrade pip

	echo '>> Updating Python packages'
	$python -m pip list --format freeze --not-required \
	| sed 's/==.*//' | grep -Fvx pip | sort -u \
	| xargs -r $python -m pip install --user --upgrade
fi

## Other
if [ -d "$0.d" ]
then
	for f in "$0.d"/*.sh
	do
		[ -r "$f" -a -x "$f" ] && . "$f"
	done
fi
