@ECHO OFF
SETLOCAL
SET BASE=%~DP0
CHDIR /D %BASE%
SET MAIN=%~1
SHIFT
SET ARGS=
:LOOP
SET ARGS=%ARGS% %~1
SHIFT
IF "%~1" NEQ "" GOTO:LOOP
cc -II:\inc -c %MAIN% %ARGS%
IF ERRORLEVEL 1 EXIT /B %ERRORLEVEL%
ENDLOCAL
