#!/bin/sh
set -e
home=$(dirname "$0")
cd $home
./lib/install
./install en% -lcore
./install fsync -lcore
./install lefix -lcore
./install printenv -lcore
./install realpath -lcore
./install un% -lcore
