@ECHO OFF
SETLOCAL
SET BASE=%~DP0
CHDIR /D %BASE%
SET MAIN=%~1
SHIFT
SET ARGS=
:LOOP
SET ARGS=%ARGS% %~1
SHIFT
IF "%~1" NEQ "" GOTO:LOOP
DEL /F /Q %MAIN%.o >NUL 2>NUL
CALL COMPILE %MAIN%.c
IF ERRORLEVEL 1 EXIT /B %ERRORLEVEL%
cc -LI:\lib -o%MAIN% %MAIN%.o %ARGS%
IF ERRORLEVEL 1 EXIT /B %ERRORLEVEL%
strip %MAIN%.exe
IF ERRORLEVEL 1 EXIT /B %ERRORLEVEL%
ENDLOCAL
