@ECHO OFF
SETLOCAL
SET BASE=%~DP0
CHDIR /D %BASE%
CALL GENERATE error.h
IF ERRORLEVEL 1 EXIT /B %ERRORLEVEL%
MKDIR I:\inc >NUL 2>NUL
COPY /Y *.h I:\inc >NUL 2>NUL
IF ERRORLEVEL 1 EXIT /B %ERRORLEVEL%
CALL GENERATE error.c
IF ERRORLEVEL 1 EXIT /B %ERRORLEVEL%
CALL GENERATE error_str.c
IF ERRORLEVEL 1 EXIT /B %ERRORLEVEL%
CALL GENERATE error_temp.c
IF ERRORLEVEL 1 EXIT /B %ERRORLEVEL%
CALL COMPILE *.c
IF ERRORLEVEL 1 EXIT /B %ERRORLEVEL%
CALL MAKELIB libcore.a *.o
IF ERRORLEVEL 1 EXIT /B %ERRORLEVEL%
MKDIR I:\lib >NUL 2>NUL
COPY /Y *.a I:\lib >NUL 2>NUL
IF ERRORLEVEL 1 EXIT /B %ERRORLEVEL%
ENDLOCAL
