@ECHO OFF
SETLOCAL
SET BASE=%~DP0
CHDIR /D %BASE%
SET MAIN=%~1
SHIFT
SET ARGS=
:LOOP
SET ARGS=%ARGS% %~1
SHIFT
IF "%~1" NEQ "" GOTO:LOOP
DEL /F /Q %MAIN% >NUL 2>NUL
ar cr %MAIN% %ARGS%
IF ERRORLEVEL 1 EXIT /B %ERRORLEVEL%
ranlib %MAIN%
IF ERRORLEVEL 1 EXIT /B %ERRORLEVEL%
ENDLOCAL
